---
- hosts: localhost

  tasks:
    - name: Read key contents
      shell: "cat {{item.keypath}}"
      register: sshkeys
      with_items: "{{ EC2list }}"
    
    - name: Create EC2 keys
      ec2_key:
        region: "{{region}}"
        name: "{{ keyname }}"
        key_material: "{{ item.stdout }} "
      with_items: "{{sshkeys.results}}"

    - name: Build All three clusters  
      ec2:
        region: "{{region}}"
        key_name: "{{item.keyname}}"
        instance_type: "{{instance_type}}"
        image: "{{image}}"
        wait: yes
        group_id: "{{security_group}}"
        count: "{{intsnace_count}}"
        vpc_subnet_id: "{{subnet_id}}"
        assign_public_ip: yes      
      with_items: "{{EC2list}}"