---
- hosts: localhost
  tasks:
    - file:
       path: "/home/aniket/.ssh/{{ item.keyname}}"
       state: absent             
      with_items: "{{ EC2list }}"             
    - file:
       path: "/home/aniket/.ssh/{{ item.keyname}}.pub"
       state: absent
      with_items: "{{ EC2list }}"      